# Server port setting
#server:
#  port: 8080

spring:
  # DB Connection Setting(DB 연결 설정)
  datasource:
    # Local DB(MySQL)
    url: jdbc:mysql://localhost:3306/between?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 0000
    # Winbit Server DB(MySQL)
#    URL: jdbc:mysql://10.1.2.171:3306/between
#    ID: root
#    pw: 1qaz2wsx!@
    driver-class-name: com.mysql.cj.jdbc.Driver
